# Vagrantfile to set up an all-in-one Hadoop cluster with a master and two worker nodes

Vagrant.configure("2") do |config|
  # Define the base configuration for all machines
  config.vm.box = "ubuntu/focal64"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y openjdk-8-jdk
    sudo apt-get install -y openssh-server
    sudo apt-get install -y rsync
  SHELL

  # Hadoop version
  hadoop_version = "3.2.1"
  # Path to the local Hadoop tar.gz file
  hadoop_tar = "hadoop-#{hadoop_version}.tar.gz"

  # Master node configuration
  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.101"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end

    master.vm.provision "shell", inline: <<-SHELL
      # Add Hadoop user
      sudo adduser --disabled-password --gecos "" hadoop
      echo "hadoop:hadoop" | sudo chpasswd
      
      # Configure SSH for Hadoop user
      sudo -u hadoop ssh-keygen -t rsa -P "" -f /home/hadoop/.ssh/id_rsa
      cat /home/hadoop/.ssh/id_rsa.pub >> /home/hadoop/.ssh/authorized_keys
      sudo chown hadoop:hadoop /home/hadoop/.ssh/authorized_keys
      sudo chmod 600 /home/hadoop/.ssh/authorized_keys
      sudo chmod 700 /home/hadoop/.ssh
      
      # Install Hadoop
      cp /vagrant/#{hadoop_tar} /home/hadoop/
      cd /home/hadoop/
      tar -xzf hadoop-3.2.1.tar.gz
      sudo mv hadoop-3.2.1 /usr/local/hadoop
      sudo chown -R hadoop:hadoop /usr/local/hadoop

      cp /vagrant/core-site.xml /usr/local/hadoop/etc/hadoop/core-site.xml
      cp /vagrant/hdfs-site.xml /usr/local/hadoop/etc/hadoop/hdfs-site.xml
      
      # Setup environment variables
      echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /home/hadoop/.bashrc
      echo "export HADOOP_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
      echo "export PATH=\$PATH:\$HADOOP_HOME/bin:\$HADOOP_HOME/sbin" >> /home/hadoop/.bashrc
      echo "export HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop" >> /home/hadoop/.bashrc
      echo "export HADOOP_MAPRED_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
      echo "export HADOOP_COMMON_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
      echo "export HADOOP_HDFS_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
      echo "export YARN_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
      source /home/hadoop/.bashrc
      
      # Set JAVA_HOME in Hadoop configuration
      echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" | sudo tee -a /usr/local/hadoop/etc/hadoop/hadoop-env.sh
      
      # Format the Namenode
      sudo -u hadoop /usr/local/hadoop/bin/hdfs namenode -format

      # Start HDFS and YARN
      sudo -u hadoop /usr/local/hadoop/sbin/start-dfs.sh
      sudo -u hadoop /usr/local/hadoop/sbin/start-yarn.sh
    SHELL
  end

  # Worker node configuration
  (1..2).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "private_network", ip: "192.168.56.10#{i + 1}"
      worker.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end

      worker.vm.provision "shell", inline: <<-SHELL
        # Add Hadoop user
        sudo adduser --disabled-password --gecos "" hadoop
        echo "hadoop:hadoop" | sudo chpasswd
        
        # Configure SSH for Hadoop user
        sudo mkdir -p /home/hadoop/.ssh
        sudo chown hadoop:hadoop /home/hadoop/.ssh
        sudo chmod 700 /home/hadoop/.ssh
        
        # Install Hadoop
        cp /vagrant/#{hadoop_tar} /home/hadoop/
        cd /home/hadoop/
        tar -xzf hadoop-3.2.1.tar.gz
        sudo mv hadoop-3.2.1 /usr/local/hadoop
        sudo chown -R hadoop:hadoop /usr/local/hadoop

        cp /vagrant/core-site.xml /usr/local/hadoop/etc/hadoop/core-site.xml
        cp /vagrant/hdfs-site.xml /usr/local/hadoop/etc/hadoop/hdfs-site.xml
        
        # Setup environment variables
        echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /home/hadoop/.bashrc
        echo "export HADOOP_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
        echo "export PATH=\$PATH:\$HADOOP_HOME/bin:\$HADOOP_HOME/sbin" >> /home/hadoop/.bashrc
        echo "export HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop" >> /home/hadoop/.bashrc
        echo "export HADOOP_MAPRED_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
        echo "export HADOOP_COMMON_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
        echo "export HADOOP_HDFS_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
        echo "export YARN_HOME=/usr/local/hadoop" >> /home/hadoop/.bashrc
        source /home/hadoop/.bashrc
        
        # Set JAVA_HOME in Hadoop configuration
        echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" | sudo tee -a /usr/local/hadoop/etc/hadoop/hadoop-env.sh
      SHELL
    end
  end
end
